---
- hosts: all
  tasks:
    - name: Install Webtatic repo
      shell: rpm -Uvh https://mirror.webtatic.com/yum/el6/latest.rpm
             creates=/etc/yum.repos.d/webtatic.repo

    - name: Install common packages
      yum: name={{ item }} state=present
      with_items:
        - git
        - gcc
        - vim
        - MySQL-python
        - nodejs
        - npm
        - mod_ssl

    - name: Install Uglify
      npm: name=uglify global=yes

    - name: Install Apache
      yum: name=httpd state=present
      notify:
        - Start Apache

    - name: Get current IPTables rules
      shell: iptables -L
      register: iptablesrules
      always_run: yes
      sudo: true

    - name: Allow port 80 on firewall
      command: /sbin/iptables -I INPUT 1 -p tcp --dport http -j ACCEPT -m comment --comment "Apache (80)"
      sudo: true
      when: iptablesrules.stdout.find("Apache (80)") == -1

    - name: Allow port 443 on firewall
      command: /sbin/iptables -I INPUT 1 -p tcp --dport https -j ACCEPT -m comment --comment "Apache (443)"
      sudo: true
      when: iptablesrules.stdout.find("Apache (443)") == -1

    - name: Save IPTables
      shell: /sbin/iptables-save > /etc/sysconfig/iptables
      sudo: true
      notify:
        - Restart IPTables

    - name: Get current IP6Tables rules
      shell: ip6tables -L
      register: ip6tablesrules
      always_run: yes
      sudo: true

    - name: Allow port 80 on firewall
      command: /sbin/ip6tables -I INPUT 1 -p tcp --dport http -j ACCEPT -m comment --comment "Apache (80)"
      sudo: true
      when: ip6tablesrules.stdout.find("Apache (80)") == -1

    - name: Allow port 443 on firewall
      command: /sbin/ip6tables -I INPUT 2 -p tcp --dport https -j ACCEPT -m comment --comment "Apache (443)"
      sudo: true
      when: ip6tablesrules.stdout.find("Apache (443)") == -1

    - name: Save IP6Tables
      shell: /sbin/ip6tables-save > /etc/sysconfig/ip6tables
      sudo: true
      notify:
        - Restart IP6Tables

    - name: Install PHP
      yum: name=php71w state=present
      notify:
        - Restart Apache

    - name: Put PHP config in place
      template: src=files/php.ini.j2 dest=/etc/php.ini

    - name: Install PHP Extensions
      yum: name={{ item }} state=present
      with_items:
        - php71w-pdo
        - php71w-mysqlnd
        - php71w-xml
      notify:
        - Restart Apache

    - name: Install MySQL
      yum: name=mysql-server state=present

    - name: Start MySQL
      service: name=mysqld state=started

    - name: Change MySQL root user pw
      mysql_user: name=root password=developing priv=*.*:ALL state=present
      ignore_errors: true

    - name: Delete anonymous MySQL server user for localhost
      mysql_user: user=""
                  state=absent
                  login_user="root"
                  login_password="developing"

    - name: Copy data
      copy: src=files/hack24.sql dest=/tmp/hack24.sql

    - name: Empty/Remove database
      mysql_db: name=hack24 login_password=hack24 login_user=hack24 state=absent

    - name: Add database
      mysql_db: name=hack24 login_password=hack24 login_user=hack24 state=present

    - name: Import data
      mysql_db: name=hack24 login_password=hack24 login_user=hack24 state=import target=/tmp/hack24.sql
      notify: Restart MySQL

    - name: Make cache directory writeable
      file: path=/var/www/html/app/cache state=directory mode=0777 recurse=yes

    - name: Make cache directory writeable (2)
      file: path=/var/www/html/app/cache/dev state=directory mode=0777 recurse=yes

    - name: Make logs directory writeable
      file: path=/var/www/html/app/logs state=directory mode=0777 recurse=yes

  handlers:
    - name: Start Apache
      service: name=httpd state=started
      sudo: true

    - name: Restart Apache
      service: name=httpd state=restarted
      sudo: true

    - name: Restart IPTables
      service: name=iptables state=restarted
      sudo: true

    - name: Restart IP6Tables
      service: name=ip6tables state=restarted
      sudo: true

    - name: Start MySQL
      service: name=mysqld state=started
      sudo: true

    - name: Restart MySQL
      service: name=mysqld state=restarted
      sudo: true
